name: Igel Build with CMake

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC versions
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12 gcc-13 g++-13

    - name: Set GCC version
      run: |
        # Set GCC 14 as the default version
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Download network file
      run: wget https://github.com/vshcherbyna/igel/releases/download/3.5.0/c049c117 -O ./network_file

    - name: Configure CMake
      run: cmake -DEVALFILE=network_file -DUSE_AVX2=1 -D_BTYPE=1 -DSYZYGY_SUPPORT=TRUE .

    - name: Build the project
      run: make -j
