name: Igel Linux Build PGO

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC versions
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12 gcc-13 g++-13

    - name: Set GCC version
      run: |
        # Set GCC 14 as the default version
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60

    - name: Run make pgo
      run: cd src&&make pgo

    - name: Run the bench
      run: cd src&&./igel bench
