name: Igel Linux Clang PGO Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "16.0"

    - name: Debug environment
      run: |
        echo $LD_LIBRARY_PATH
        echo $LLVMgold
        ls /path/to/llvm/lib

    - name: Build the PGO build
      run: cd src&&make pgo

    - name: Run the bench
      run: cd src&&./igel bench
